# Generated by Django 2.2.7 on 2019-11-11 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MutualFund',
            new_name='Portfolio',
        ),
    ]
