# Generated by Django 2.2.7 on 2019-11-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191111_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detail',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
