# Generated by Django 2.2.7 on 2019-11-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191111_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='password',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
