# Generated by Django 2.2.7 on 2019-11-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_detail_password'),
    ]

    operations = [
    ]
